language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true


after_success: |
    cargo doc \
    && echo '<meta http-equiv=refresh content=0;url=slack_verify/index.html>' > target/doc/index.html


deploy:
    provider: pages
    local-dir: target/doc
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
        branch: master
